url: "https://15440.courses.cs.cmu.edu"
baseurl: ""

# Theme settings
doks:
    baseurl: ""
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: "15-440 Distributed Systems"
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Schedule
              item_url: '/schedule'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Assignments
              item_url: '/assignments'
            - item_name: Recitations
              item_url: '/recitations'
            - item_name: Past Exams
              item_url: '/past-exams'
            # - item_name: FAQ
            #   item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2026. Carnegie Mellon University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            # - network_name: youtube
            #   profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/


# Course logistics
course:
    semester: Fall 2026
    time: Tue/Thu 11:00-12:20 in CUC MCCNMY
    venue:
    edstem: &es 'https://edstem.org/us/courses/102065'
    gradescope: &gs 'https://www.gradescope.com/courses/1352034'
    pollev: &pe 'https://pollev.com/cmu15440'
    queuestatus:
        url: &qs 'https://ohq.eberly.cmu.edu/#/'
        name: '15-440 (Fall 2026)'
    canvas: 'https://canvas.cmu.edu/'
    project_timeline:
        proposal: 2020-04-22T23:59:00-07:00
        milestone1: 2020-05-08T23:59:00-07:00
        milestone2: 2020-05-22T23:59:00-07:00
        poster_and_report: 2020-06-12T23:59:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        project-2019-fall:
            icon:
            content: Fall 2019
            url: '/past-projects/#fall-2019'
            external_url: false
        project-2020-win:
            icon:
            content: Winter 2020
            url: '/past-projects/#winter-2020'
            external_url: false
        video2018:
            icon:
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false
        edstem:
            icon:
            content: Edstem
            url: *es 
            external_url: true
        pollev:
            icon:
            content: PollEv
            url: *pe
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/117317/external_tools/5384'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
        gradescope:
            icon:
            content: Gradescope
            url: *gs
            external_url: true

    staff:
        - name: Charlie Garrod
          type: Instructor
          url: https://www.cs.cmu.edu/~charlie/
          image: charlie.jpg
          email: charlie@cs.cmu.edu
        - name: Yuvraj Agarwal
          type: Instructor
          url: https://www.synergylabs.org/yuvraj/
          image: yuvraj.png
          email: yuvraj@cs.cmu.edu
        - name: Ben Titzer
          type: Instructor
          url: https://s3d.cmu.edu/people/core-faculty/titzer-ben.html
          image: titzer.png
          email: btitzer@andrew.cmu.edu          

    ta:
        - name: Aditya Chanana
          email: achanana@andrew.cmu.edu
          type: TA
          image: achanana.jpg
        - name: Alejandro Estrada
          email: alejande@andrew.cmu.edu
          type: TA
          image: alejande.jpeg
        - name: Alex Xu
          email: alexxu@andrew.cmu.edu
          type: TA
          image: alexxu.png
        - name: Arin Bhandari
          email: arinb@andrew.cmu.edu
          type: TA
          image: arinb.jpg
        - name: Bert Shan
          email: bshan@andrew.cmu.edu
          type: TA
          image: bshan.jpg
        - name: Bhargav Kommireddy
          email: bkommire@andrew.cmu.edu
          type: TA
          image: bkommire.jpeg
        - name: Cindy Wang
          email: cindywan@andrew.cmu.edu
          type: TA
          image: silhouette.png
        - name: Daryl Lavin
          email: daryllav@andrew.cmu.edu
          type: TA
          image: daryllav.jpg
        - name: Dillon Shelton
          email: dillonsh@andrew.cmu.edu
          type: TA
          image: dillonsh.jpeg
        - name: Isaac Au
          email: yau@andrew.cmu.edu
          type: TA
          image: yau.jpg
        - name: Jeslyn Koay
          email: tkoay@andrew.cmu.edu
          type: TA
          image: tkoay.jpg
        - name: Maggie Gong
          email: yiyug@andrew.cmu.edu
          type: TA
          image: yiyug.jpg
        - name: Mert Iren
          email: miren@andrew.cmu.edu
          type: TA
          image: miren.jpeg
        - name: Nathan Chen
          email: nuodec@andrew.cmu.edu
          type: TA
          image: nuodec.jpg
        - name: Nick Yaeger
          email: nyaeger@andrew.cmu.edu
          type: TA
          image: nyaeger.jpg
        - name: Rohaib Cheema
          email: rcheema@andrew.cmu.edu
          type: TA
          image: silhouette.png
        - name: Sean Lim
          email: seanlim@andrew.cmu.edu
          type: TA
          image: seanlim.png
        - name: Varun Donde
          email: vdonde@andrew.cmu.edu
          type: TA
          image: vdonde.jpeg
        - name: William Li
          email: wl4@andrew.cmu.edu
          type: TA
          image: wl4.jpg
        - name: Zak Kent
          email: zkent@andrew.cmu.edu
          type: TA
          image: zkent.jpeg





